### ISSUE TITLE
Allow user to view hadith-book summaries

### ISSUE THREAD

**Issue by Zir0-93** [rewayaat/rewayaat#26]
While browsing hadith, users should have the ability to click on a book title in order to view a short summary of the book.

**Comment by rewayaat** [comment]
Implemented by commit: [19eda556a3f34ffdc63e2a13d2b15bc82737520b31](https://github.com/rewayaat/rewayaat/commit/9eda556a3f34ffdc63e2a13d2b15bc82737520b3)
