### ISSUE TITLE
UI improvement: Chapter, section, and volume attributes should be clickable for futher exploration

### ISSUE THREAD

**Issue by Zir0-93** [rewayaat/rewayaat#40]
When displaying hadith, attributes like Chapter, Section, and Volume should be links that users can click on to explore hadith specifically from that Chapter, Section or Volume respectively. At the moment, these attributes are just displayed as plain text.

**Comment by rewayaat** [comment]
Depends on #42

**Comment by Zir0-93** [comment]
Implemented, closing
